// <auto-generated />
using DatabaseSync.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseSync.Migrations.ServerDb
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseSync.Persistence.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Email = "john@example.com",
                            Name = "John Doe",
                            Phone = "1234567890"
                        },
                        new
                        {
                            CustomerID = 2,
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            Phone = "0987654321"
                        },
                        new
                        {
                            CustomerID = 3,
                            Email = "alice@example.com",
                            Name = "Alice Johnson",
                            Phone = "1122334455"
                        },
                        new
                        {
                            CustomerID = 4,
                            Email = "bob@example.com",
                            Name = "Bob Brown",
                            Phone = "2233445566"
                        },
                        new
                        {
                            CustomerID = 5,
                            Email = "charlie@example.com",
                            Name = "Charlie White",
                            Phone = "3344556677"
                        },
                        new
                        {
                            CustomerID = 6,
                            Email = "david@example.com",
                            Name = "David Green",
                            Phone = "4455667788"
                        },
                        new
                        {
                            CustomerID = 7,
                            Email = "eve@example.com",
                            Name = "Eve Blue",
                            Phone = "5566778899"
                        },
                        new
                        {
                            CustomerID = 8,
                            Email = "frank@example.com",
                            Name = "Frank Black",
                            Phone = "6677889900"
                        },
                        new
                        {
                            CustomerID = 9,
                            Email = "grace@example.com",
                            Name = "Grace Silver",
                            Phone = "7788990011"
                        },
                        new
                        {
                            CustomerID = 10,
                            Email = "hank@example.com",
                            Name = "Hank Gold",
                            Phone = "8899001122"
                        },
                        new
                        {
                            CustomerID = 11,
                            Email = "ivy@example.com",
                            Name = "Ivy Red",
                            Phone = "9900112233"
                        },
                        new
                        {
                            CustomerID = 12,
                            Email = "jake@example.com",
                            Name = "Jake Violet",
                            Phone = "1010101010"
                        },
                        new
                        {
                            CustomerID = 13,
                            Email = "liam@example.com",
                            Name = "Liam Orange",
                            Phone = "1111111111"
                        },
                        new
                        {
                            CustomerID = 14,
                            Email = "mia@example.com",
                            Name = "Mia Cyan",
                            Phone = "1212121212"
                        },
                        new
                        {
                            CustomerID = 15,
                            Email = "noah@example.com",
                            Name = "Noah Brown",
                            Phone = "1313131313"
                        },
                        new
                        {
                            CustomerID = 16,
                            Email = "olivia@example.com",
                            Name = "Olivia Pink",
                            Phone = "1414141414"
                        },
                        new
                        {
                            CustomerID = 17,
                            Email = "peter@example.com",
                            Name = "Peter Gray",
                            Phone = "1515151515"
                        },
                        new
                        {
                            CustomerID = 18,
                            Email = "quinn@example.com",
                            Name = "Quinn Magenta",
                            Phone = "1616161616"
                        },
                        new
                        {
                            CustomerID = 19,
                            Email = "ryan@example.com",
                            Name = "Ryan Lime",
                            Phone = "1717171717"
                        },
                        new
                        {
                            CustomerID = 20,
                            Email = "sophia@example.com",
                            Name = "Sophia Peach",
                            Phone = "1818181818"
                        });
                });

            modelBuilder.Entity("DatabaseSync.Persistence.Entities.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            Address = "Address 1 - 1",
                            CustomerID = 1
                        },
                        new
                        {
                            LocationID = 2,
                            Address = "Address 1 - 2",
                            CustomerID = 1
                        },
                        new
                        {
                            LocationID = 3,
                            Address = "Address 1 - 3",
                            CustomerID = 1
                        },
                        new
                        {
                            LocationID = 4,
                            Address = "Address 2 - 1",
                            CustomerID = 2
                        },
                        new
                        {
                            LocationID = 5,
                            Address = "Address 2 - 2",
                            CustomerID = 2
                        },
                        new
                        {
                            LocationID = 6,
                            Address = "Address 2 - 3",
                            CustomerID = 2
                        },
                        new
                        {
                            LocationID = 7,
                            Address = "Address 3 - 1",
                            CustomerID = 3
                        },
                        new
                        {
                            LocationID = 8,
                            Address = "Address 3 - 2",
                            CustomerID = 3
                        },
                        new
                        {
                            LocationID = 9,
                            Address = "Address 3 - 3",
                            CustomerID = 3
                        },
                        new
                        {
                            LocationID = 10,
                            Address = "Address 4 - 1",
                            CustomerID = 4
                        },
                        new
                        {
                            LocationID = 11,
                            Address = "Address 4 - 2",
                            CustomerID = 4
                        },
                        new
                        {
                            LocationID = 12,
                            Address = "Address 4 - 3",
                            CustomerID = 4
                        },
                        new
                        {
                            LocationID = 13,
                            Address = "Address 5 - 1",
                            CustomerID = 5
                        },
                        new
                        {
                            LocationID = 14,
                            Address = "Address 5 - 2",
                            CustomerID = 5
                        },
                        new
                        {
                            LocationID = 15,
                            Address = "Address 5 - 3",
                            CustomerID = 5
                        },
                        new
                        {
                            LocationID = 16,
                            Address = "Address 6 - 1",
                            CustomerID = 6
                        },
                        new
                        {
                            LocationID = 17,
                            Address = "Address 6 - 2",
                            CustomerID = 6
                        },
                        new
                        {
                            LocationID = 18,
                            Address = "Address 6 - 3",
                            CustomerID = 6
                        },
                        new
                        {
                            LocationID = 19,
                            Address = "Address 7 - 1",
                            CustomerID = 7
                        },
                        new
                        {
                            LocationID = 20,
                            Address = "Address 7 - 2",
                            CustomerID = 7
                        },
                        new
                        {
                            LocationID = 21,
                            Address = "Address 7 - 3",
                            CustomerID = 7
                        },
                        new
                        {
                            LocationID = 22,
                            Address = "Address 8 - 1",
                            CustomerID = 8
                        },
                        new
                        {
                            LocationID = 23,
                            Address = "Address 8 - 2",
                            CustomerID = 8
                        },
                        new
                        {
                            LocationID = 24,
                            Address = "Address 8 - 3",
                            CustomerID = 8
                        },
                        new
                        {
                            LocationID = 25,
                            Address = "Address 9 - 1",
                            CustomerID = 9
                        },
                        new
                        {
                            LocationID = 26,
                            Address = "Address 9 - 2",
                            CustomerID = 9
                        },
                        new
                        {
                            LocationID = 27,
                            Address = "Address 9 - 3",
                            CustomerID = 9
                        },
                        new
                        {
                            LocationID = 28,
                            Address = "Address 10 - 1",
                            CustomerID = 10
                        },
                        new
                        {
                            LocationID = 29,
                            Address = "Address 10 - 2",
                            CustomerID = 10
                        },
                        new
                        {
                            LocationID = 30,
                            Address = "Address 10 - 3",
                            CustomerID = 10
                        },
                        new
                        {
                            LocationID = 31,
                            Address = "Address 11 - 1",
                            CustomerID = 11
                        },
                        new
                        {
                            LocationID = 32,
                            Address = "Address 11 - 2",
                            CustomerID = 11
                        },
                        new
                        {
                            LocationID = 33,
                            Address = "Address 11 - 3",
                            CustomerID = 11
                        },
                        new
                        {
                            LocationID = 34,
                            Address = "Address 12 - 1",
                            CustomerID = 12
                        },
                        new
                        {
                            LocationID = 35,
                            Address = "Address 12 - 2",
                            CustomerID = 12
                        },
                        new
                        {
                            LocationID = 36,
                            Address = "Address 12 - 3",
                            CustomerID = 12
                        },
                        new
                        {
                            LocationID = 37,
                            Address = "Address 13 - 1",
                            CustomerID = 13
                        },
                        new
                        {
                            LocationID = 38,
                            Address = "Address 13 - 2",
                            CustomerID = 13
                        },
                        new
                        {
                            LocationID = 39,
                            Address = "Address 13 - 3",
                            CustomerID = 13
                        },
                        new
                        {
                            LocationID = 40,
                            Address = "Address 14 - 1",
                            CustomerID = 14
                        },
                        new
                        {
                            LocationID = 41,
                            Address = "Address 14 - 2",
                            CustomerID = 14
                        },
                        new
                        {
                            LocationID = 42,
                            Address = "Address 14 - 3",
                            CustomerID = 14
                        },
                        new
                        {
                            LocationID = 43,
                            Address = "Address 15 - 1",
                            CustomerID = 15
                        },
                        new
                        {
                            LocationID = 44,
                            Address = "Address 15 - 2",
                            CustomerID = 15
                        },
                        new
                        {
                            LocationID = 45,
                            Address = "Address 15 - 3",
                            CustomerID = 15
                        },
                        new
                        {
                            LocationID = 46,
                            Address = "Address 16 - 1",
                            CustomerID = 16
                        },
                        new
                        {
                            LocationID = 47,
                            Address = "Address 16 - 2",
                            CustomerID = 16
                        },
                        new
                        {
                            LocationID = 48,
                            Address = "Address 16 - 3",
                            CustomerID = 16
                        },
                        new
                        {
                            LocationID = 49,
                            Address = "Address 17 - 1",
                            CustomerID = 17
                        },
                        new
                        {
                            LocationID = 50,
                            Address = "Address 17 - 2",
                            CustomerID = 17
                        },
                        new
                        {
                            LocationID = 51,
                            Address = "Address 17 - 3",
                            CustomerID = 17
                        },
                        new
                        {
                            LocationID = 52,
                            Address = "Address 18 - 1",
                            CustomerID = 18
                        },
                        new
                        {
                            LocationID = 53,
                            Address = "Address 18 - 2",
                            CustomerID = 18
                        },
                        new
                        {
                            LocationID = 54,
                            Address = "Address 18 - 3",
                            CustomerID = 18
                        },
                        new
                        {
                            LocationID = 55,
                            Address = "Address 19 - 1",
                            CustomerID = 19
                        },
                        new
                        {
                            LocationID = 56,
                            Address = "Address 19 - 2",
                            CustomerID = 19
                        },
                        new
                        {
                            LocationID = 57,
                            Address = "Address 19 - 3",
                            CustomerID = 19
                        },
                        new
                        {
                            LocationID = 58,
                            Address = "Address 20 - 1",
                            CustomerID = 20
                        },
                        new
                        {
                            LocationID = 59,
                            Address = "Address 20 - 2",
                            CustomerID = 20
                        },
                        new
                        {
                            LocationID = 60,
                            Address = "Address 20 - 3",
                            CustomerID = 20
                        });
                });

            modelBuilder.Entity("DatabaseSync.Persistence.Entities.Location", b =>
                {
                    b.HasOne("DatabaseSync.Persistence.Entities.Customer", "Customer")
                        .WithMany("Locations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DatabaseSync.Persistence.Entities.Customer", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
